# 查找 OpenGL 库（跨平台）
find_package(OpenGL REQUIRED)
if(NOT OpenGL_FOUND)
    message(FATAL_ERROR "OpenGL not found! Please install OpenGL development libraries.")
endif()

# 删除第三方库的测试构建
set(ASSIMP_BUILD_TESTS OFF)
set(GLFW_BUILD_TESTS OFF)
set(SPDLOG_BUILD_TESTS OFF)

# 启用文件夹功能（Visual Studio专用？）
set_property(GLOBAL PROPERTY USE_FOLDERS ON)

# 定义第三方库的筛选器名称
set(THIRDPARTY_FOLDER "ThirdParty")
set(MATERIALX_FOLDER "MaterialX")

# 添加第三方目录
add_subdirectory(thirdparty/glfw)
add_subdirectory(thirdparty/spdlog)
add_subdirectory(thirdparty/assimp)
add_subdirectory(thirdparty/meshoptimizer)
add_subdirectory(thirdparty/materialx)
add_subdirectory(thirdparty/googletest)

include_directories(thirdparty/glm)
include_directories(thirdparty/glad)
include_directories(thirdparty/stduuid)
include_directories(thirdparty/stduuid/include)
include_directories(thirdparty/cereal/include)
include_directories(thirdparty/stbimg)
include_directories(thirdparty/json/single_include)
include_directories(thirdparty/threadpool/include)

# shaderc需要依赖spirv_tools等其他第三方库
# spirv_tools又需要手动将spirv_headers放到指定目录
file(COPY "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/spirv_headers/"
     DESTINATION "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/spirv_tools/external/spirv-headers"
)
add_subdirectory(thirdparty/spirv_tools)
add_subdirectory(thirdparty/glslang)
add_subdirectory(thirdparty/shaderc)

# imgui和imguizmo无cmakelist，为避免污染依赖库，此处手动添加
include(imgui.cmake)
include(imguizmo.cmake)

# 为第三方库设置文件夹属性
if(TARGET spdlog)
    set_target_properties(spdlog PROPERTIES FOLDER ${THIRDPARTY_FOLDER})
endif()
if(TARGET assimp)
    set_target_properties(assimp PROPERTIES FOLDER ${THIRDPARTY_FOLDER})
endif()
if(TARGET unit)
    set_target_properties(unit PROPERTIES FOLDER ${THIRDPARTY_FOLDER})
endif()
if(TARGET UpdateAssimpLibsDebugSymbolsAndDLLs)
    set_target_properties(UpdateAssimpLibsDebugSymbolsAndDLLs PROPERTIES FOLDER ${THIRDPARTY_FOLDER})
endif()
if(TARGET zlibstatic)
    set_target_properties(zlibstatic PROPERTIES FOLDER ${THIRDPARTY_FOLDER})
endif()
if(TARGET Imgui)
    set_target_properties(Imgui PROPERTIES FOLDER ${THIRDPARTY_FOLDER})
endif()
if(TARGET ImGuizmo)
    set_target_properties(ImGuizmo PROPERTIES FOLDER ${THIRDPARTY_FOLDER})
endif()
if(TARGET meshoptimizer)
    set_target_properties(meshoptimizer PROPERTIES FOLDER ${THIRDPARTY_FOLDER})
endif()
if(TARGET gmock)
    set_target_properties(gmock PROPERTIES FOLDER ${THIRDPARTY_FOLDER})
endif()
if(TARGET gmock_main)
    set_target_properties(gmock_main PROPERTIES FOLDER ${THIRDPARTY_FOLDER})
endif()
if(TARGET gtest)
    set_target_properties(gtest PROPERTIES FOLDER ${THIRDPARTY_FOLDER})
endif()
if(TARGET gtest_main)
    set_target_properties(gtest_main PROPERTIES FOLDER ${THIRDPARTY_FOLDER})
endif()
if(TARGET MaterialXCore)
    set_target_properties(MaterialXCore PROPERTIES FOLDER ${MATERIALX_FOLDER})
endif()
if(TARGET MaterialXFormat)
    set_target_properties(MaterialXFormat PROPERTIES FOLDER ${MATERIALX_FOLDER})
endif()
if(TARGET MaterialXGenGlsl)
    set_target_properties(MaterialXGenGlsl PROPERTIES FOLDER ${MATERIALX_FOLDER})
endif()
if(TARGET MaterialXGenMdl)
    set_target_properties(MaterialXGenMdl PROPERTIES FOLDER ${MATERIALX_FOLDER})
endif()
if(TARGET MaterialXGenMsl)
    set_target_properties(MaterialXGenMsl PROPERTIES FOLDER ${MATERIALX_FOLDER})
endif()
if(TARGET MaterialXGenOsl)
    set_target_properties(MaterialXGenOsl PROPERTIES FOLDER ${MATERIALX_FOLDER})
endif()
if(TARGET MaterialXGenShader)
    set_target_properties(MaterialXGenShader PROPERTIES FOLDER ${MATERIALX_FOLDER})
endif()
if(TARGET MaterialXRender)
    set_target_properties(MaterialXRender PROPERTIES FOLDER ${MATERIALX_FOLDER})
endif()
if(TARGET MaterialXRenderGlsl)
    set_target_properties(MaterialXRenderGlsl PROPERTIES FOLDER ${MATERIALX_FOLDER})
endif()
if(TARGET MaterialXRenderHw)
    set_target_properties(MaterialXRenderHw PROPERTIES FOLDER ${MATERIALX_FOLDER})
endif()
if(TARGET MaterialXRenderOsl)
    set_target_properties(MaterialXRenderOsl PROPERTIES FOLDER ${MATERIALX_FOLDER})
endif()