# 查找 OpenGL 库（跨平台）
find_package(OpenGL REQUIRED)
if(NOT OpenGL_FOUND)
    message(FATAL_ERROR "OpenGL not found! Please install OpenGL development libraries.")
endif()

# 删除第三方库的测试构建
set(ASSIMP_BUILD_TESTS OFF)
set(GLFW_BUILD_TESTS OFF)
set(SPDLOG_BUILD_TESTS OFF)
set(SHADERC_SKIP_TESTS ON)
set(SPIRV_SKIP_TESTS ON)

# 启用文件夹功能（Visual Studio专用？）
set_property(GLOBAL PROPERTY USE_FOLDERS ON)

# 添加第三方目录
add_subdirectory(thirdparty/glfw)
add_subdirectory(thirdparty/spdlog)
add_subdirectory(thirdparty/assimp)
add_subdirectory(thirdparty/meshoptimizer)
add_subdirectory(thirdparty/googletest)

include_directories(thirdparty/glm)
include_directories(thirdparty/glad)
include_directories(thirdparty/stduuid)
include_directories(thirdparty/stduuid/include)
include_directories(thirdparty/cereal/include)
include_directories(thirdparty/stbimg)
include_directories(thirdparty/json/single_include)
include_directories(thirdparty/threadpool/include)

# imgui和imguizmo无cmakelist，为避免污染依赖库，此处手动添加
# imguifuledialog通过find_package寻找imgui，故手动实现，不依赖其自带的cmake文件
include(imgui.cmake)
include(imguizmo.cmake)
include(imguifiledialog.cmake)

# ============================================
# Shaderc 依赖自动同步
# ============================================
set(SHADERC_DEPS_SYNCED FALSE)
# 检查是否需要同步依赖
if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/shaderc/third_party/glslang/CMakeLists.txt")
    message(STATUS "Shaderc dependencies already exist, skipping sync")
    set(SHADERC_DEPS_SYNCED TRUE)
else()
    message(STATUS "Shaderc dependencies not found, will sync automatically")
endif()
# 如果依赖不存在，自动同步
if(NOT SHADERC_DEPS_SYNCED)
    # 查找 Python3
    find_package(Python3 COMPONENTS Interpreter)
    
    if(Python3_Interpreter_FOUND)
        message(STATUS "Found Python3: ${Python3_EXECUTABLE}")
        
        # 获取 shaderc 目录
        set(SHADERC_DIR "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/shaderc")
        
        # 检查 git-sync-deps 脚本是否存在
        if(EXISTS "${SHADERC_DIR}/utils/git-sync-deps")
            message(STATUS "Running git-sync-deps for Shaderc...")
            
            # 执行同步命令
            execute_process(
                COMMAND ${Python3_EXECUTABLE} utils/git-sync-deps
                WORKING_DIRECTORY ${SHADERC_DIR}
                RESULT_VARIABLE SYNC_RESULT
                OUTPUT_VARIABLE SYNC_OUTPUT
                ERROR_VARIABLE SYNC_ERROR
                OUTPUT_STRIP_TRAILING_WHITESPACE
                ERROR_STRIP_TRAILING_WHITESPACE
            )
            
            if(SYNC_RESULT EQUAL 0)
                message(STATUS "Shaderc dependencies synced successfully")
                message(STATUS "Output: ${SYNC_OUTPUT}")
                set(SHADERC_DEPS_SYNCED TRUE)
            else()
                message(WARNING "Failed to sync Shaderc dependencies")
                message(WARNING "Error: ${SYNC_ERROR}")
                message(WARNING "You may need to manually run: cd thirdparty/shaderc && python3 utils/git-sync-deps")
            endif()
        else()
            message(WARNING "git-sync-deps script not found at ${SHADERC_DIR}/utils/git-sync-deps")
            message(WARNING "Please ensure you have the full Shaderc repository")
        endif()
    else()
        message(WARNING "Python3 not found! Cannot auto-sync Shaderc dependencies")
        message(WARNING "Please install Python3 and ensure it's in PATH, or manually run:")
        message(WARNING "  cd thirdparty/shaderc && python3 utils/git-sync-deps")
    endif()
endif()
# 检查依赖是否就绪，然后添加 shaderc
if(SHADERC_DEPS_SYNCED OR EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/shaderc/third_party/glslang/CMakeLists.txt")
    message(STATUS "Adding Shaderc to build...")
    add_subdirectory(thirdparty/shaderc)
else()
    message(WARNING "Shaderc dependencies not available, skipping Shaderc build")
    message(WARNING "You can manually sync dependencies with:")
    message(WARNING "  cd thirdparty/shaderc && python3 utils/git-sync-deps")
    message(WARNING "Then reconfigure CMake")
endif()


# ============================================
# 为第三方库设置文件夹属性
# ============================================
set(THIRDPARTY_FOLDER "ThirdParty")
if(TARGET spdlog)
    set_target_properties(spdlog PROPERTIES FOLDER ${THIRDPARTY_FOLDER})
endif()
if(TARGET assimp)
    set_target_properties(assimp PROPERTIES FOLDER ${THIRDPARTY_FOLDER})
endif()
if(TARGET unit)
    set_target_properties(unit PROPERTIES FOLDER ${THIRDPARTY_FOLDER})
endif()
if(TARGET UpdateAssimpLibsDebugSymbolsAndDLLs)
    set_target_properties(UpdateAssimpLibsDebugSymbolsAndDLLs PROPERTIES FOLDER ${THIRDPARTY_FOLDER})
endif()
if(TARGET zlibstatic)
    set_target_properties(zlibstatic PROPERTIES FOLDER ${THIRDPARTY_FOLDER})
endif()
if(TARGET Imgui)
    set_target_properties(Imgui PROPERTIES FOLDER ${THIRDPARTY_FOLDER})
endif()
if(TARGET ImGuizmo)
    set_target_properties(ImGuizmo PROPERTIES FOLDER ${THIRDPARTY_FOLDER})
endif()
if(TARGET ImGuiFileDialog)
    set_target_properties(ImGuiFileDialog PROPERTIES FOLDER ${THIRDPARTY_FOLDER})
endif()
if(TARGET meshoptimizer)
    set_target_properties(meshoptimizer PROPERTIES FOLDER ${THIRDPARTY_FOLDER})
endif()
if(TARGET gmock)
    set_target_properties(gmock PROPERTIES FOLDER ${THIRDPARTY_FOLDER})
endif()
if(TARGET gmock_main)
    set_target_properties(gmock_main PROPERTIES FOLDER ${THIRDPARTY_FOLDER})
endif()
if(TARGET gtest)
    set_target_properties(gtest PROPERTIES FOLDER ${THIRDPARTY_FOLDER})
endif()
if(TARGET gtest_main)
    set_target_properties(gtest_main PROPERTIES FOLDER ${THIRDPARTY_FOLDER})
endif()

# ShaderC
set(SHADERC_FOLDER "ShadercFolder")
if(TARGET add-copyright)
    set_target_properties(add-copyright PROPERTIES FOLDER ${SHADERC_FOLDER})
endif()
if(TARGET build-version)
    set_target_properties(build-version PROPERTIES FOLDER ${SHADERC_FOLDER})
endif()
if(TARGET check-copyright)
    set_target_properties(check-copyright PROPERTIES FOLDER ${SHADERC_FOLDER})
endif()
if(TARGET core_tables)
    set_target_properties(core_tables PROPERTIES FOLDER ${SHADERC_FOLDER})
endif()
if(TARGET extinst_tables)
    set_target_properties(extinst_tables PROPERTIES FOLDER ${SHADERC_FOLDER})
endif()
if(TARGET glslc)
    set_target_properties(glslc PROPERTIES FOLDER ${SHADERC_FOLDER})
endif()
if(TARGET glslc_exe)
    set_target_properties(glslc_exe PROPERTIES FOLDER ${SHADERC_FOLDER})
endif()
if(TARGET shaderc)
    set_target_properties(shaderc PROPERTIES FOLDER ${SHADERC_FOLDER})
endif()
if(TARGET shaderc_combined)
    set_target_properties(shaderc_combined PROPERTIES FOLDER ${SHADERC_FOLDER})
endif()
if(TARGET shaderc_combined-pkg-config)
    set_target_properties(shaderc_combined-pkg-config PROPERTIES FOLDER ${SHADERC_FOLDER})
endif()
if(TARGET shaderc_shared)
    set_target_properties(shaderc_shared PROPERTIES FOLDER ${SHADERC_FOLDER})
endif()
if(TARGET shaderc_static-pkg-config)
    set_target_properties(shaderc_static-pkg-config PROPERTIES FOLDER ${SHADERC_FOLDER})
endif()
if(TARGET shaderc_util)
    set_target_properties(shaderc_util PROPERTIES FOLDER ${SHADERC_FOLDER})
endif()
if(TARGET shaderc-online-compile)
    set_target_properties(shaderc-online-compile PROPERTIES FOLDER ${SHADERC_FOLDER})
endif()
if(TARGET shaderc-pkg-config)
    set_target_properties(shaderc-pkg-config PROPERTIES FOLDER ${SHADERC_FOLDER})
endif()
if(TARGET spirv-tools-check-python-tests)
    set_target_properties(spirv-tools-check-python-tests PROPERTIES FOLDER ${SHADERC_FOLDER})
endif()
if(TARGET spirv-tools-check-python-types)
    set_target_properties(spirv-tools-check-python-types PROPERTIES FOLDER ${SHADERC_FOLDER})
endif()
if(TARGET spirv-tools-pkg-config)
    set_target_properties(spirv-tools-pkg-config PROPERTIES FOLDER ${SHADERC_FOLDER})
endif()
if(TARGET spirv-tools-tables)
    set_target_properties(spirv-tools-tables PROPERTIES FOLDER ${SHADERC_FOLDER})
endif()
if(TARGET testdata)
    set_target_properties(testdata PROPERTIES FOLDER ${SHADERC_FOLDER})
endif()


set(GLSLANG_FOLDER "${SHADERC_FOLDER}/glslang")
if(TARGET GenericCodeGen)
    set_target_properties(GenericCodeGen PROPERTIES FOLDER ${GLSLANG_FOLDER})
endif()
if(TARGET glslang)
    set_target_properties(glslang PROPERTIES FOLDER ${GLSLANG_FOLDER})
endif()
if(TARGET glslang-default-resource-limits)
    set_target_properties(glslang-default-resource-limits PROPERTIES FOLDER ${GLSLANG_FOLDER})
endif()
if(TARGET MachineIndependent)
    set_target_properties(MachineIndependent PROPERTIES FOLDER ${GLSLANG_FOLDER})
endif()
if(TARGET OSDependent)
    set_target_properties(OSDependent PROPERTIES FOLDER ${GLSLANG_FOLDER})
endif()
if(TARGET SPIRV)
    set_target_properties(SPIRV PROPERTIES FOLDER ${GLSLANG_FOLDER})
endif()
if(TARGET glslang-standalone)
    set_target_properties(glslang-standalone PROPERTIES FOLDER ${GLSLANG_FOLDER})
endif()

set(SPIRV_TOOLS_FOLDER "${SHADERC_FOLDER}/spirv-tools")
if(TARGET spirv-tools-build-version)
    set_target_properties(spirv-tools-build-version PROPERTIES FOLDER ${SPIRV_TOOLS_FOLDER})
endif()
if(TARGET spirv-tools-header-DebugInfo)
    set_target_properties(spirv-tools-header-DebugInfo PROPERTIES FOLDER ${SPIRV_TOOLS_FOLDER})
endif()
if(TARGET spirv-tools-header-NonSemanticShaderDebugInfo100)
    set_target_properties(spirv-tools-header-NonSemanticShaderDebugInfo100 PROPERTIES FOLDER ${SPIRV_TOOLS_FOLDER})
endif()
if(TARGET spirv-tools-header-OpenCLDebugInfo100)
    set_target_properties(spirv-tools-header-OpenCLDebugInfo100 PROPERTIES FOLDER ${SPIRV_TOOLS_FOLDER})
endif()
if(TARGET spirv-tools-cpp-example)
    set_target_properties(spirv-tools-cpp-example PROPERTIES FOLDER ${SPIRV_TOOLS_FOLDER})
endif()
if(TARGET spirv-as)
    set_target_properties(spirv-as PROPERTIES FOLDER ${SPIRV_TOOLS_FOLDER})
endif()
if(TARGET spirv-cfg)
    set_target_properties(spirv-cfg PROPERTIES FOLDER ${SPIRV_TOOLS_FOLDER})
endif()
if(TARGET spirv-diff)
    set_target_properties(spirv-diff PROPERTIES FOLDER ${SPIRV_TOOLS_FOLDER})
endif()
if(TARGET spirv-dis)
    set_target_properties(spirv-dis PROPERTIES FOLDER ${SPIRV_TOOLS_FOLDER})
endif()
if(TARGET spirv-link)
    set_target_properties(spirv-link PROPERTIES FOLDER ${SPIRV_TOOLS_FOLDER})
endif()
if(TARGET spirv-lint)
    set_target_properties(spirv-lint PROPERTIES FOLDER ${SPIRV_TOOLS_FOLDER})
endif()
if(TARGET spirv-objdump)
    set_target_properties(spirv-objdump PROPERTIES FOLDER ${SPIRV_TOOLS_FOLDER})
endif()
if(TARGET spirv-opt)
    set_target_properties(spirv-opt PROPERTIES FOLDER ${SPIRV_TOOLS_FOLDER})
endif()
if(TARGET spirv-reduce)
    set_target_properties(spirv-reduce PROPERTIES FOLDER ${SPIRV_TOOLS_FOLDER})
endif()
if(TARGET spirv-val)
    set_target_properties(spirv-val PROPERTIES FOLDER ${SPIRV_TOOLS_FOLDER})
endif()
if(TARGET SPIRV-Tools-diff)
    set_target_properties(SPIRV-Tools-diff PROPERTIES FOLDER ${SPIRV_TOOLS_FOLDER})
endif()
if(TARGET SPIRV-Tools-link)
    set_target_properties(SPIRV-Tools-link PROPERTIES FOLDER ${SPIRV_TOOLS_FOLDER})
endif()
if(TARGET SPIRV-Tools-lint)
    set_target_properties(SPIRV-Tools-lint PROPERTIES FOLDER ${SPIRV_TOOLS_FOLDER})
endif()
if(TARGET SPIRV-Tools-opt)
    set_target_properties(SPIRV-Tools-opt PROPERTIES FOLDER ${SPIRV_TOOLS_FOLDER})
endif()
if(TARGET SPIRV-Tools-reduce)
    set_target_properties(SPIRV-Tools-reduce PROPERTIES FOLDER ${SPIRV_TOOLS_FOLDER})
endif()
if(TARGET SPIRV-Tools-shared)
    set_target_properties(SPIRV-Tools-shared PROPERTIES FOLDER ${SPIRV_TOOLS_FOLDER})
endif()
if(TARGET SPIRV-Tools-static)
    set_target_properties(SPIRV-Tools-static PROPERTIES FOLDER ${SPIRV_TOOLS_FOLDER})
endif()
if(TARGET spirv-tools-vimsyntax)
    set_target_properties(spirv-tools-vimsyntax PROPERTIES FOLDER ${SPIRV_TOOLS_FOLDER})
endif()
