# 创建可执行目标，添加其他源文件
add_subdirectory(command)
add_subdirectory(core)
add_subdirectory(data)
add_subdirectory(event)
add_subdirectory(input)
add_subdirectory(light)
add_subdirectory(material)
add_subdirectory(renderer)
add_subdirectory(scene_core)
add_subdirectory(scene_graph)
add_subdirectory(scene_serializer)
add_subdirectory(scene_view)
add_subdirectory(window)
add_subdirectory(ui)