# .github/workflows/macos_build.yml
name: MacOS Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Setup Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Ninja
      run: |
        # 安装Ninja构建工具
        brew install ninja
        
        # 安装GLFW库(Macos专用, 由于GLFW在MacOS上默认使用Cocoa,依赖OBJCXX,所以无法通过ninja手动编译GLFW Submodule)
        brew install glfw

    - name: Build
      run: |
        # 创建构建目录
        mkdir -p build && cd build
        
        # 配置并构建
        # 强制GLFW使用Cocoa后端
        cmake -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DGLFW_BUILD_X11=OFF \
          -DGLFW_BUILD_COCOA=ON \
          ..
        ninja
    
    - name: Test
      run: |
        cd build
        # macOS兼容的find命令
        find . -name "*test*" -type f -perm +111 -exec {} \;